### ISSUE TITLE
Resolve Conflict errors

### ISSUE THREAD

**Issue by teeedor** [JCKortlang/ScheduleMe#20]
I encountered a bug that happens when reserving an appointment with two separate companies. First, sign in, and make a new appointment with any company on any day at any time. Now make a new appointment with a different company and when you choose a date, all time slots of that day should be conflicting. I am not sure of the extent of the bug.

**Comment by JCKortlang** [comment]
I am not able to replicate this.

**Comment by teeedor** [comment]
Ok, I'll try to see if I can make it happen again today in office hours

**Comment by JCKortlang** [comment]
I lied. I found the bug. :+1:  Its fixed.

**Comment by teeedor** [comment]
Oh cool
